networks:
  mqtt-network:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    # restart: always
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mosquitto:/mosquitto/config:rw
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt-network

  domoticz:
    image: domoticz/domoticz:stable
    hostname: domoticz
    container_name: domoticz
    # restart: always
    depends_on:
      - mosquitto
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./domoticz:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - mqtt-network

  hardware-client:
    container_name: hardware-client
    depends_on:
      - mosquitto
    # restart: no
    build:
      context: ./hardware-client
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 80:80
    networks:
      - mqtt-network
