networks:
  mqtt-network:
    driver: bridge

services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: on-failure:5
    env_file: .env
    ports:
      - 1883:1883 #default mqtt port
      - 9001:9001 #default mqtt port for websockets
    networks:
      - mqtt-network

  domoticz:
    image: domoticz/domoticz:stable
    hostname: domoticz
    container_name: domoticz
    restart: on-failure:5
    depends_on:
      - mosquitto
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - ./domoticz:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - mqtt-network

  hardware-client:
    container_name: hardware-client
    build:
      context: ./hardware-client
      dockerfile: Dockerfile
    restart: on-failure:5
    depends_on:
      - domoticz
    env_file: .env
    ports:
      - 80:80
    networks:
      - mqtt-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
